export const CONVERSATION_DELETE_ERROR_CODES = {
  ACTIVE_AGENT_RUN: 'CONVERSATION_DELETE_BLOCKED_ACTIVE_AGENT_RUN',
  ACTIVE_CAPABILITY_JOB: 'CONVERSATION_DELETE_BLOCKED_ACTIVE_CAPABILITY_JOB',
} as const;

export type ConversationDeleteErrorCode =
  typeof CONVERSATION_DELETE_ERROR_CODES[keyof typeof CONVERSATION_DELETE_ERROR_CODES];

export const PROJECT_DELETE_ERROR_CODES = {
  PROTECTED_PROJECT: 'PROJECT_DELETE_BLOCKED_PROTECTED_PROJECT',
  ACTIVE_AGENT_RUN: 'PROJECT_DELETE_BLOCKED_ACTIVE_AGENT_RUN',
  ACTIVE_CAPABILITY_JOB: 'PROJECT_DELETE_BLOCKED_ACTIVE_CAPABILITY_JOB',
} as const;

export type ProjectDeleteErrorCode =
  typeof PROJECT_DELETE_ERROR_CODES[keyof typeof PROJECT_DELETE_ERROR_CODES];
