export function getCrawlerSkillMarkdown(): string {
  return [
    '---',
    'name: crawler',
    'description: Guide structured crawling with the Obscura Browser Tool.',
    'when_to_use: Use when the user needs structured web crawling, link discovery, pagination, or repeated extraction from rendered web pages.',
    '---',
    '',
    '# Crawler Skill',
    '',
    'Use this Skill to plan and run structured crawling workflows through the Obscura Browser Tool.',
    '',
    'This Skill contains strategy only. Do not call Obscura through shell commands or wrapper scripts; every page read, link discovery step, cookie inspection, asset inspection, and source read goes through `obscura_browse`.',
    '',
    '## Tool Use',
    '',
    '- Use `obscura_browse` with `format: "markdown"`, `format: "text"`, or `format: "html"` for rendered page content.',
    '- Use `obscura_browse` with `format: "links"` for link discovery before following pagination or detail pages.',
    '- Use `obscura_browse` with `format: "cookies"` only to inspect whether a site sets relevant read-state cookies; do not attempt login or session reuse.',
    '- Use `obscura_browse` with `format: "assets"` when images, PDFs, scripts, or other asset URLs are part of the extraction target.',
    '- Use `obscura_browse` with `format: "original"` for the raw, unrendered HTTP response body — for example JSON endpoints, feeds, or other non-HTML resources. It bypasses browser rendering entirely; to verify extraction or debug selectors against the rendered page, use `format: "html"` instead.',
    '- Use the Fetch Tool instead of Obscura for simple static URL reads that do not need a browser environment.',
    '',
    '## Four Questions Before Crawling',
    '',
    '### Define the target',
    '',
    '- State the source site, seed URL or URL pattern, expected page types, and stop condition.',
    '- Identify whether the task needs listing pages, detail pages, downloadable assets, or all of them.',
    '- Keep each crawl bounded by count, date range, category, URL prefix, or another explicit limit.',
    '',
    '### Define the extraction schema',
    '',
    '- Decide the output fields before collecting records.',
    '- For each field, describe the source evidence: page title, heading, table cell, link text, metadata, asset URL, or surrounding text.',
    '- Include `sourceUrl` on every record and keep nullable fields explicit when evidence is missing.',
    '',
    '### Define the traversal plan',
    '',
    '- Start with one seed page and inspect links before expanding.',
    '- Prefer deterministic pagination links and URL patterns over broad link following.',
    '- Deduplicate URLs before fetching them, and keep a visited set for the current task.',
    '- Stop when the requested bound is reached, pagination ends, or pages stop producing new records.',
    '',
    '### Define the access posture',
    '',
    '- Respect robots.txt by default.',
    '- Keep concurrency low and add a delay between repeated requests.',
    '- Use `stealth: true` by default for browser fingerprint consistency, not to bypass access controls.',
    '- Do not work around login walls, paywalls, CAPTCHAs, rate limits, or other access controls unless the user states they have legitimate access and explicitly asks for that route.',
    '',
    '## Output Discipline',
    '',
    '- Write each extracted record as JSONL or Markdown as soon as it is validated, according to the current task destination.',
    '- Attach the source URL to every record and include enough nearby evidence for later verification.',
    '- Report partial progress with counts for fetched pages, skipped pages, extracted records, and failures.',
    '- When a page is ambiguous, save the source URL and a short note instead of inventing missing fields.',
    '- If the user did not specify an output location, return a concise summary plus the records in the response rather than creating a project artifact.',
  ].join('\n');
}
