export function getKnowledgeBaseAgentsBlock(): string {
  return [
    '<!-- CDF:knowledge-base:start -->',
    '## Knowledge Base',
    '',
    '在以下情况使用 Knowledge Base Skill：',
    '- 用户要求记住、保存、记录、沉淀或复用项目知识；',
    '- 任务产出了可复用的决策、调研、实现发现、故障排查步骤或项目约定；',
    '- 工作流导入、整理或总结了后续应可检索的外部资料；',
    '- 新增项目知识前，先搜索已有 Knowledge Entries，避免重复。',
    '',
    'Knowledge Base 位于 `.cdf/knowledge/`。',
    '<!-- CDF:knowledge-base:end -->',
  ].join('\n');
}

export function getKnowledgeBaseSkillMarkdown(): string {
  const agentsBlock = getKnowledgeBaseAgentsBlock();
  return [
    '---',
    'name: knowledge-base',
    'description: Enable and use the project Knowledge Base for durable project knowledge.',
    'when_to_use: Use when the user asks to remember, save, document, preserve, organize, or reuse project knowledge.',
    '---',
    '',
    '# Knowledge Base Skill',
    '',
    'Use this Skill to enable and maintain a project-local Knowledge Base.',
    '',
    '## Enable the Knowledge Base',
    '',
    'When the user asks to enable the Knowledge Base for the project:',
    '',
    '1. Ensure `.cdf/knowledge/` exists.',
    '2. Ensure `.cdf/knowledge/index.md` and `.cdf/knowledge/log.md` exist.',
    '3. Read the project `AGENTS.md` if it exists; if it does not exist, create it.',
    '4. Add or update only the Knowledge Base managed block delimited by:',
    '',
    '<!-- CDF:knowledge-base:start -->',
    '<!-- CDF:knowledge-base:end -->',
    '',
    'This managed block is required for enablement. Do not report that the Knowledge Base is enabled until `AGENTS.md` contains the managed block.',
    'If you also seed initial Knowledge Entries for an existing project, write and verify the `AGENTS.md` managed block first, then create entries.',
    '',
    'Use this exact managed block content:',
    '',
    agentsBlock,
    '',
    'Preserve all user-authored `AGENTS.md` content outside the managed block.',
    '',
    '## Use the Knowledge Base',
    '',
    '- Use `knowledge_search` before adding entries to avoid duplicates.',
    '- Use `knowledge_create` to create new Knowledge Entries with OKF frontmatter.',
    '- New entries use OKF `type`, `title`, optional `description`, optional `resource`, `tags`, and `timestamp` metadata.',
    '- Do not invent `source.type: agent`; `source` is not part of the CDF-managed OKF metadata.',
    '- Use file tools to read, update, or delete existing entries after confirming the target.',
    '- Do not treat `index.md` or `log.md` as Knowledge Entries.',
    '- `knowledge_create` does not update `log.md`; append a short log note only for meaningful additions, imports, or reorganizations.',
  ].join('\n');
}
