import React, { useState, useMemo } from 'react';
import { useTranslation } from 'react-i18next';
import { Check, Copy, Terminal, FileCode, WrapText, ListOrdered, ChevronDown, ChevronUp } from 'lucide-react';
import Prism from 'prismjs';

// Load Prism components for syntax highlighting support
import 'prismjs/components/prism-javascript';
import 'prismjs/components/prism-typescript';
import 'prismjs/components/prism-python';
import 'prismjs/components/prism-bash';
import 'prismjs/components/prism-json';
import 'prismjs/components/prism-go';
import 'prismjs/components/prism-rust';
import 'prismjs/components/prism-yaml';
import 'prismjs/components/prism-sql';

export interface CodeBlockProps {
  lang: string;
  code: string;
}

type Token = string | Prism.Token;

interface FlatToken {
  type: string;
  content: string;
}

// Map short language codes to human-readable names
function formatLangName(lang: string): string {
  if (!lang) return 'code';
  const mapping: Record<string, string> = {
    js: 'javascript',
    ts: 'typescript',
    jsx: 'react jsx',
    tsx: 'react tsx',
    py: 'python',
    python: 'python',
    sh: 'shell',
    bash: 'bash',
    shell: 'shell',
    json: 'json',
    html: 'html',
    css: 'css',
    rs: 'rust',
    rust: 'rust',
    go: 'go',
    golang: 'go',
    yml: 'yaml',
    yaml: 'yaml',
    sql: 'sql',
    md: 'markdown',
    markdown: 'markdown',
  };
  return mapping[lang.toLowerCase()] || lang.toLowerCase();
}

// Display icons based on language types
function LanguageIcon({ lang, className }: { lang: string; className?: string }) {
  const lower = (lang || '').toLowerCase();
  if (['sh', 'bash', 'shell', 'zsh'].includes(lower)) {
    return <Terminal className={className} />;
  }
  return <FileCode className={className} />;
}

export function CodeBlock({ lang, code }: CodeBlockProps) {
  const { t } = useTranslation();
  const [copied, setCopied] = useState(false);
  const [showLineNumbers, setShowLineNumbers] = useState(true);
  const [wordWrap, setWordWrap] = useState(false);
  
  // Strip trailing empty lines commonly generated by LLMs
  const cleanCode = useMemo(() => {
    return code.replace(/\n$/, '');
  }, [code]);

  const [isCollapsed, setIsCollapsed] = useState(() => {
    // Collapse code automatically if it spans more than 15 lines
    const lineCount = cleanCode.split('\n').length;
    return lineCount > 15;
  });

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(cleanCode);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy text: ', err);
    }
  };

  // 1. Process Prism tokens and split them recursively into structured lines
  const lineTokensList = useMemo(() => {
    const cleanLang = (lang || '').toLowerCase();
    let grammar: Prism.Grammar | undefined = Prism.languages[cleanLang];
    if (!grammar) {
      const alias: Record<string, string> = {
        js: 'javascript',
        ts: 'typescript',
        py: 'python',
        sh: 'bash',
        bash: 'bash',
        shell: 'bash',
        go: 'go',
        rs: 'rust',
        yml: 'yaml',
      };
      const mappedLang = alias[cleanLang];
      grammar = mappedLang ? Prism.languages[mappedLang] : undefined;
    }

    if (!grammar) {
      // Fallback: split raw text into plain tokens line-by-line
      return cleanCode.split('\n').map(line => [{ type: 'plain', content: line || ' ' }]);
    }

    const tokens = Prism.tokenize(cleanCode, grammar);
    const lines: FlatToken[][] = [[]];

    function processToken(token: Token, parentType = 'plain') {
      if (typeof token === 'string') {
        const parts = token.split('\n');
        parts.forEach((part, index) => {
          if (index > 0) {
            lines.push([]);
          }
          if (part) {
            lines[lines.length - 1].push({
              type: parentType,
              content: part
            });
          } else if (index > 0 || parts.length > 1) {
            lines[lines.length - 1].push({
              type: 'plain',
              content: ' '
            });
          }
        });
      } else {
        const type = token.type;
        // Handle array contents or leaf tokens recursively
        if (Array.isArray(token.content)) {
          token.content.forEach(subToken => processToken(subToken, `${parentType} ${type}`));
        } else {
          processToken(token.content as Token, `${parentType} ${type}`);
        }
      }
    }

    tokens.forEach(token => processToken(token));
    return lines;
  }, [cleanCode, lang]);

  // 2. Render code lines with wrap states
  const renderedLines = useMemo(() => {
    return lineTokensList.map((lineTokens, lineIdx) => (
      <div
        key={lineIdx}
        className="code-line group/line flex items-start px-4 transition-colors duration-100 hover:bg-[var(--color-bg-hover)]"
        style={{ minHeight: '1.6rem', lineHeight: '1.6rem' }}
      >
        <span className={`flex-1 ${wordWrap ? 'whitespace-pre-wrap break-all' : 'whitespace-pre'}`}>
          {lineTokens.map((t, tokenIdx) => (
            <span key={tokenIdx} className={`token ${t.type}`}>
              {t.content}
            </span>
          ))}
        </span>
      </div>
    ));
  }, [lineTokensList, wordWrap]);

  return (
    <div className="group/code relative my-4 border border-[var(--color-border)]/60 rounded-lg overflow-hidden font-mono text-xs bg-[var(--color-bg-sidebar)] transition-all duration-200 shadow-sm">
      {/* Header controls bar */}
      <div className="flex justify-between items-center px-4 py-2 bg-[var(--color-bg-sunken)] text-[var(--color-text-secondary)] border-b border-[var(--color-border)]/50 select-none">
        <div className="flex items-center gap-2">
          <LanguageIcon lang={lang} className="w-3.5 h-3.5 text-[var(--color-text-muted)]" />
          <span className="uppercase text-[11px] font-bold tracking-wider text-[var(--color-text-primary)]">
            {formatLangName(lang)}
          </span>
        </div>

        <div className="flex items-center gap-1">
          {/* Word Wrap Toggle */}
          <button
            type="button"
            title={t('codeBlock.wrapLines')}
            onClick={() => setWordWrap(!wordWrap)}
            className={`p-1 rounded cursor-pointer transition-colors hover:bg-[var(--color-bg-hover)] hover:text-[var(--color-text-primary)] active:scale-[0.95] ${
              wordWrap ? 'text-[var(--color-accent)] bg-[var(--color-accent-dim)]' : 'text-[var(--color-text-secondary)]'
            }`}
          >
            <WrapText className="w-3.5 h-3.5" />
          </button>

          {/* Line Numbers Toggle */}
          <button
            type="button"
            title={t('codeBlock.lineNumbers')}
            onClick={() => setShowLineNumbers(!showLineNumbers)}
            className={`p-1 rounded cursor-pointer transition-colors hover:bg-[var(--color-bg-hover)] hover:text-[var(--color-text-primary)] active:scale-[0.95] ${
              showLineNumbers ? 'text-[var(--color-accent)] bg-[var(--color-accent-dim)]' : 'text-[var(--color-text-secondary)]'
            }`}
          >
            <ListOrdered className="w-3.5 h-3.5" />
          </button>

          <div className="w-[1px] h-3 bg-[var(--color-border)]/50 mx-1" />

          {/* Copy Button */}
          <button
            type="button"
            title={copied ? t('codeBlock.copied') : t('codeBlock.copy')}
            onClick={handleCopy}
            className={`transition-[background-color,color,transform] duration-150 p-1 rounded cursor-pointer flex items-center gap-1 active:scale-[0.95] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-accent)] ${
              copied
                ? 'text-[var(--color-success)] bg-[var(--color-success-dim)]'
                : 'text-[var(--color-text-secondary)] hover:text-[var(--color-text-primary)] hover:bg-[var(--color-bg-hover)]'
            }`}
          >
            {copied ? (
              <Check className="w-3.5 h-3.5 text-[var(--color-success)] animate-pop-in" />
            ) : (
              <Copy className="w-3.5 h-3.5" />
            )}
          </button>
        </div>
      </div>

      {/* Code Container with Collapsible controls */}
      <div
        className="relative overflow-hidden transition-all duration-300 ease-in-out bg-[var(--color-bg-sidebar)] flex"
        style={{ maxHeight: isCollapsed ? '280px' : 'none' }}
      >
        {/* Left fixed Line Numbers gutter */}
        {showLineNumbers && (
          <div
            className="select-none text-right shrink-0 flex flex-col py-4 bg-[var(--color-bg-sunken)]/60 border-r border-[var(--color-border)]/40 text-[var(--color-text-muted)] opacity-65 z-10"
            style={{ width: '2.5rem', paddingRight: '0.75rem' }}
          >
            {lineTokensList.map((_, idx) => (
              <div key={idx} className="font-mono text-xs text-right" style={{ height: '1.6rem', lineHeight: '1.6rem' }}>
                {idx + 1}
              </div>
            ))}
          </div>
        )}

        <pre className={`flex-1 py-4 text-[var(--color-text-primary)] ${wordWrap ? 'whitespace-pre-wrap break-all' : 'overflow-x-auto'}`} style={{ background: 'transparent', margin: 0 }}>
          <code className={`block min-w-full ${wordWrap ? 'whitespace-pre-wrap break-all' : 'whitespace-pre'}`} style={{ background: 'transparent', padding: 0, borderRadius: 0 }}>
            {renderedLines}
          </code>
        </pre>

        {/* Gradual blur overlay for collapsed state */}
        {isCollapsed && (
          <div className="absolute bottom-0 left-0 right-0 h-16 bg-gradient-to-t from-[var(--color-bg-sidebar)] to-transparent flex items-end justify-center pb-3 select-none z-20">
            <button
              type="button"
              onClick={() => setIsCollapsed(false)}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-full border border-[var(--color-border)] bg-[var(--color-bg-surface)] text-[11px] font-semibold text-[var(--color-text-secondary)] hover:text-[var(--color-text-primary)] hover:border-[var(--color-border-strong)] transition-all cursor-pointer shadow-sm active:scale-95 hover:shadow"
            >
              {t('codeBlock.expand')}
              <ChevronDown className="w-3.5 h-3.5 text-[var(--color-text-muted)]" />
            </button>
          </div>
        )}
      </div>

      {/* Expand state helper floating collapse button */}
      {!isCollapsed && lineTokensList.length > 15 && (
        <button
          type="button"
          onClick={() => setIsCollapsed(true)}
          className="absolute bottom-3 right-3 opacity-0 group-hover/code:opacity-100 transition-opacity duration-200 flex items-center gap-1 px-2.5 py-1.5 rounded border border-[var(--color-border)] bg-[var(--color-bg-surface)] text-[10px] text-[var(--color-text-secondary)] hover:text-[var(--color-text-primary)] cursor-pointer shadow-sm active:scale-95 hover:shadow"
        >
          {t('codeBlock.collapse')}
          <ChevronUp className="w-3.5 h-3.5 text-[var(--color-text-muted)]" />
        </button>
      )}
    </div>
  );
}